name = "wordle-espanol"
compatibility_date = "2025-08-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
pages_build_output_dir = ".open-next/assets"

[assets]
directory = ".open-next/assets"
binding = "STATIC_ASSETS"
